---
name: Lint and check styling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm prettier:check
      - run: pnpm type-check
